version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Build Artifact
          command: |
            pwd
            ls -al
            cd webapp/
            mvn -P aws clean package -DskipTests
            cd target/
            ls -al
            cd ../../..
      - run:
          name: Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            mkdir -p artifact


      - run:
          name: Upload Artifact to S3
          command: |
            echo "Hello"
      - run:
          name: Make CodeDeploy API call
          command: |
            echo "Hello CodeDeploy" 