version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install Packages
          command: |
            sudo apt-get update && sudo apt-get -y install wget zip unzip python3
            python3 --version
      - run:
          name: Install pip
          command: sudo apt install python3-pip
      - run:
          name: Install AWS CLI
          command: |
            pip3 --version
            sudo pip3 install awscli
            aws --version
      - run:
          name: Build Artifact
          command: |
            pwd
            ls -al
            cd webapp/
            mvn -P aws clean package -DskipTests
            cd target/
            ls -al
            cd ../../..
      - run:
          name: Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            mkdir -p artifact
            zip -r csye6225-web-app-${CIRCLE_BUILD_NUM}.zip webapp/target/ROOT.war infrastructure/aws/codedeploy/*.sh *.yaml
            mv csye6225-web-app-${CIRCLE_BUILD_NUM}.zip artifact
            cd artifact
            ls -al
      - run:
          name: Upload Artifact to S3
          command: |
            aws s3 sync artifact s3://${BUCKET_NAME}
      - run:
          name: Make CodeDeploy API call
          command: |
            echo "Hello CodeDeploy"
            aws deploy create-deployment --application-name csye6225 \
                        --deployment-config-name CodeDeployDefault.AllAtOnce \
                        --deployment-group-name csye6225-deployment \
                        --description "CSYE6255 - CodeDeploy" \
                        --s3-location bucket=${BUCKET_NAME},key=csye6225-web-app-${CIRCLE_BUILD_NUM}.zip,bundleType=zip \
                        --region us-east-1 \
                        --output json